In [23]:
import pandas as pd
import requests
import numpy as np


def NotUnitcode(x):
    if x[:2] != 'U+':
        return np.nan
    else:
        return x


url = 'https://unicode.org/emoji/charts/full-emoji-list.html'


html = pd.read_html(url)
df = html[0]

col = []
for i in range(15):
    col.append(df.columns[i][2])


df.columns = col
df['Code'] = df['Code'].map(lambda x: x[:7]).copy()
df['U_Code'] = df['Code'].apply(NotUnitcode)
emoji = df[~df['U_Code'].isna()][['Code','Browser','CLDR Short Name']].reset_index(drop=True)
emoji.to_csv('emoji.csv',index = False)

In [24]:
df = pd.read_csv("emoji.csv")
df.head(10)

      Code Browser                  CLDR Short Name
0  U+1F600       üòÄ                    grinning face
1  U+1F603       üòÉ      grinning face with big eyes
2  U+1F604       üòÑ  grinning face with smiling eyes
3  U+1F601       üòÅ   beaming face with smiling eyes
4  U+1F606       üòÜ          grinning squinting face
5  U+1F605       üòÖ         grinning face with sweat
6  U+1F923       ü§£    rolling on the floor laughing
7  U+1F602       üòÇ           face with tears of joy
8  U+1F642       üôÇ            slightly smiling face
9  U+1F643       üôÉ                 upside-down face

In [25]:
df["category"] = 0
df

         Code  Browser                  CLDR Short Name  category
0     U+1F600        üòÄ                    grinning face         0
1     U+1F603        üòÉ      grinning face with big eyes         0
2     U+1F604        üòÑ  grinning face with smiling eyes         0
3     U+1F601        üòÅ   beaming face with smiling eyes         0
4     U+1F606        üòÜ          grinning squinting face         0
...       ...      ...                              ...       ...
1848  U+1F1FF       üáøüá≤                     flag: Zambia         0
1849  U+1F1FF       üáøüáº                   flag: Zimbabwe         0
1850  U+1F3F4  üè¥Û†ÅßÛ†Å¢Û†Å•Û†ÅÆÛ†ÅßÛ†Åø                    flag: England         0
1851  U+1F3F4  üè¥Û†ÅßÛ†Å¢Û†Å≥Û†Å£Û†Å¥Û†Åø                   flag: Scotland         0
1852  U+1F3F4  üè¥Û†ÅßÛ†Å¢Û†Å∑Û†Å¨Û†Å≥Û†Åø                      flag: Wales         0

[1853 rows x 4 columns]

In [26]:
#Í∞ÄÏ°±
for i in range(493,519):
    df.loc[i, 'category'] = 'Í∞ÄÏ°±'

In [27]:
#Ïó¨ÏÑ±
df.loc[237, 'category'] = 'Ïó¨ÏÑ±'
df.loc[238, 'category'] = 'Ïó¨ÏÑ±'
df.loc[240, 'category'] = 'Ïó¨ÏÑ±'
df.loc[242, 'category'] = 'Ïó¨ÏÑ±'
df.loc[246, 'category'] = 'Ïó¨ÏÑ±'
df.loc[250, 'category'] = 'Ïó¨ÏÑ±'
df.loc[253, 'category'] = 'Ïó¨ÏÑ±'
df.loc[256, 'category'] = 'Ïó¨ÏÑ±'
df.loc[259, 'category'] = 'Ïó¨ÏÑ±'
df.loc[262, 'category'] = 'Ïó¨ÏÑ±'
df.loc[265, 'category'] = 'Ïó¨ÏÑ±'
df.loc[268, 'category'] = 'Ïó¨ÏÑ±'
df.loc[277, 'category'] = 'Ïó¨ÏÑ±'
df.loc[280, 'category'] = 'Ïó¨ÏÑ±'
df.loc[356, 'category'] = 'Ïó¨ÏÑ±'
df.loc[387, 'category'] = 'Ïó¨ÏÑ±'
df.loc[400, 'category'] = 'Ïó¨ÏÑ±'

In [28]:
#ÎÇ®ÏÑ±
df.loc[229, 'category'] = 'ÎÇ®ÏÑ±'
df.loc[231, 'category'] = 'ÎÇ®ÏÑ±'
df.loc[233, 'category'] = 'ÎÇ®ÏÑ±'
df.loc[234, 'category'] = 'ÎÇ®ÏÑ±'
df.loc[235, 'category'] = 'ÎÇ®ÏÑ±'
df.loc[236, 'category'] = 'ÎÇ®ÏÑ±'
df.loc[247, 'category'] = 'ÎÇ®ÏÑ±'
df.loc[249, 'category'] = 'ÎÇ®ÏÑ±'
df.loc[252, 'category'] = 'ÎÇ®ÏÑ±'
df.loc[255, 'category'] = 'ÎÇ®ÏÑ±'
df.loc[258, 'category'] = 'ÎÇ®ÏÑ±'
df.loc[261, 'category'] = 'ÎÇ®ÏÑ±'
df.loc[264, 'category'] = 'ÎÇ®ÏÑ±'
df.loc[267, 'category'] = 'ÎÇ®ÏÑ±'
df.loc[276, 'category'] = 'ÎÇ®ÏÑ±'
df.loc[279, 'category'] = 'ÎÇ®ÏÑ±'
df.loc[346, 'category'] = 'ÎÇ®ÏÑ±'

In [29]:
#ÏÑ±ÏÜåÏàòÏûê
df.loc[488, 'category'] = 'ÏÑ±ÏÜåÏàòÏûê'
df.loc[489, 'category'] = 'ÏÑ±ÏÜåÏàòÏûê'
df.loc[492, 'category'] = 'ÏÑ±ÏÜåÏàòÏûê'
df.loc[493, 'category'] = 'ÏÑ±ÏÜåÏàòÏûê'
df.loc[500, 'category'] = 'ÏÑ±ÏÜåÏàòÏûê'
df.loc[502, 'category'] = 'ÏÑ±ÏÜåÏàòÏûê'
df.loc[503, 'category'] = 'ÏÑ±ÏÜåÏàòÏûê'
df.loc[505, 'category'] = 'ÏÑ±ÏÜåÏàòÏûê'
df.loc[506, 'category'] = 'ÏÑ±ÏÜåÏàòÏûê'
df.loc[507, 'category'] = 'ÏÑ±ÏÜåÏàòÏûê'
df.loc[508, 'category'] = 'ÏÑ±ÏÜåÏàòÏûê'

In [30]:
#Ïù∏Ï¢Ö
df.loc[108, 'category'] = 'Ïù∏Ï¢Ö'
df.loc[109, 'category'] = 'Ïù∏Ï¢Ö'
df.loc[110, 'category'] = 'Ïù∏Ï¢Ö'
df.loc[112, 'category'] = 'Ïù∏Ï¢Ö'
df.loc[114, 'category'] = 'Ïù∏Ï¢Ö'

In [31]:
#Íµ≠Ï†Å
for i in range(1692,1712):
    df.loc[i, 'category'] = 'Íµ≠Ï†Å'

In [32]:
#Ïó∞Î†π
df.loc[223, 'category'] = 'Ïó∞Î†π'
df.loc[224, 'category'] = 'Ïó∞Î†π'
df.loc[225, 'category'] = 'Ïó∞Î†π'
df.loc[226, 'category'] = 'Ïó∞Î†π'
df.loc[235, 'category'] = 'Ïó∞Î†π'
df.loc[248, 'category'] = 'Ïó∞Î†π'
df.loc[249, 'category'] = 'Ïó∞Î†π'
df.loc[250, 'category'] = 'Ïó∞Î†π'

In [33]:
#ÏßÄÏó≠
df.loc[827, 'category'] = 'ÏßÄÏó≠'
df.loc[828, 'category'] = 'ÏßÄÏó≠'
df.loc[829, 'category'] = 'ÏßÄÏó≠'
df.loc[830, 'category'] = 'ÏßÄÏó≠'
df.loc[831, 'category'] = 'ÏßÄÏó≠'
df.loc[805, 'category'] = 'ÏßÄÏó≠'
df.loc[806, 'category'] = 'ÏßÄÏó≠'
df.loc[808, 'category'] = 'ÏßÄÏó≠'
df.loc[809, 'category'] = 'ÏßÄÏó≠'

In [34]:
#Ï¢ÖÍµê
for i in range(1410,1422):
    df.loc[i, 'category'] = 'Ï¢ÖÍµê'

In [35]:
#Í∏∞ÌÉÄÌòêÏò§
df.loc[1379, 'category'] = 'Í∏∞ÌÉÄÌòêÏò§'
df.loc[1380, 'category'] = 'Í∏∞ÌÉÄÌòêÏò§'
df.loc[1385, 'category'] = 'Í∏∞ÌÉÄÌòêÏò§'
df.loc[1377, 'category'] = 'Í∏∞ÌÉÄÌòêÏò§'

In [36]:
#ÏïÖÌîå
df.loc[1193, 'category'] = 'ÏïÖÌîå'
df.loc[1191, 'category'] = 'ÏïÖÌîå'

In [37]:
#ÏöïÏÑ§
df.loc[102, 'category'] = 'ÏöïÏÑ§'
df.loc[100, 'category'] = 'ÏöïÏÑ§'

In [38]:
#Í∞úÏù∏ÏßÄÏπ≠
df.loc[182, 'category'] = 'Í∞úÏù∏ÏßÄÏπ≠'
df.loc[183, 'category'] = 'Í∞úÏù∏ÏßÄÏπ≠'

In [41]:
unness = df[df["category"] == 0].index
df.drop(unness)

         Code Browser          CLDR Short Name category
100   U+1F620       üò†               angry face       ÏöïÏÑ§
102   U+1F608       üòà  smiling face with horns       ÏöïÏÑ§
108   U+1F479       üëπ                     ogre       Ïù∏Ï¢Ö
109   U+1F47A       üë∫                   goblin       Ïù∏Ï¢Ö
110   U+1F47B       üëª                    ghost       Ïù∏Ï¢Ö
...       ...     ...                      ...      ...
1707  U+1F1EE      üáÆüáπ              flag: Italy       Íµ≠Ï†Å
1708  U+1F1EF      üáØüá™             flag: Jersey       Íµ≠Ï†Å
1709  U+1F1EF      üáØüá≤            flag: Jamaica       Íµ≠Ï†Å
1710  U+1F1EF      üáØüá¥             flag: Jordan       Íµ≠Ï†Å
1711  U+1F1EF      üáØüáµ              flag: Japan       Íµ≠Ï†Å

[124 rows x 4 columns]